apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-data-distributed-coordinator-ed.name" . }}-peer
  labels:
    {{- include "eric-data-distributed-coordinator-ed.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-distributed-coordinator-ed.annotations" . | nindent 4 }}
spec:
{{- if or (eq (include "eric-data-distributed-coordinator-ed.internalIPFamily" .) "IPv4") (eq (include "eric-data-distributed-coordinator-ed.internalIPFamily" .) "IPv6") }}
  # ipFamilies was introduced in K8s v1.20
  ipFamilies: [{{- include "eric-data-distributed-coordinator-ed.internalIPFamily" . | quote }}]
  ipFamilyPolicy: SingleStack
{{- else }}
  ipFamilyPolicy: PreferDualStack
{{- end }}
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ include "eric-data-distributed-coordinator-ed.ports.peer" . }}
      name: peer-port
  selector:
{{- include "eric-data-distributed-coordinator-ed.selectorLabels" . | indent 2 }}
