apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-data-distributed-coordinator-ed.service-account.name" . }}
  labels:
    {{- include "eric-data-distributed-coordinator-ed.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-distributed-coordinator-ed.annotations" . | nindent 4 }}
automountServiceAccountToken: false