{{- if eq (include "eric-data-distributed-coordinator-ed.hkln.executor" .) "service" -}}
{{- $helmHook := dict -}}
{{- $_ := set $helmHook "helm.sh/hook" "pre-rollback" -}}
{{- $_ := set $helmHook "helm.sh/hook-weight" "-203" -}} {{- /* Must run before any hooklauncher job !!! */ -}}
{{- $commonAnn := fromYaml (include "eric-data-distributed-coordinator-ed.hkln.annotations" .) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-data-distributed-coordinator-ed.hkln.name" . }}-rb
  labels:
    {{- include "eric-data-distributed-coordinator-ed.hkln.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-distributed-coordinator-ed.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHook $commonAnn)) | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eric-data-distributed-coordinator-ed.hkln.name" . }}-role
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ template "eric-data-distributed-coordinator-ed.hkln.name" . }}-sa
{{- end -}}