{{- if and (eq (include "eric-data-distributed-coordinator-ed.networkPolicy" .) "true") (.Values.brAgent.enabled) -}}
# Policy for brAgent connecting to DCED
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-data-distributed-coordinator-ed.name" . }}-agent-allow
  labels: {{- include "eric-data-distributed-coordinator-ed.labels" . | nindent 4}}
  annotations: {{- include "eric-data-distributed-coordinator-ed.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-data-distributed-coordinator-ed.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ template "eric-data-distributed-coordinator-ed.agentName" . }}
    ports:
    - port: {{- include "eric-data-distributed-coordinator-ed.ports.client" . | nindent 8 }}
      protocol: TCP
{{- end }}