repository: eridoca
# ADP Reference Microservice folder:
folderId: 0b004cffc50cc850
documents:
  - title: "Distributed Coordinator ED User Guide"
    file: "./build/doc/user-guide/user_guide.pdf"
    source_files:
      - "./doc/user-guide/user_guide.md"
      - "./doc/user-guide/DistributedCoordinatorED_architecture_overview.png"
      - "./doc/user-guide/DistributedCoordinatorED_deployment.png"
      - "./doc/user-guide/DistributedCoordinatorED_deployment_overview.png"
    decimal-class: "1553"
    class-prefix: "1"
    individual-number: "APR 201 59/2"
    eri_document_type: "User Guide"
    lang: "en"
    format: "pdf"
  - title: "Distributed Coordinator ED {semver} Test Report"
    object_name: "Distributed Coordinator ED {semver} Test Report"
    file: "./build/doc-archive/test-report.zip"
    decimal-class: "152 83"
    class-prefix: ""
    individual-number: "APR 201 59/2"
    eri_document_type: "Test Report"
    strategy: "ordinal"
    lang: "en"
    format: "zip"
  - title: "Distributed Coordinator ED Developers Guide"
    file: "./build/doc/developers-guide/DistributedCoordinatorED_Developers_Guide.pdf"
    source_files:
      - "./doc/developers-guide/DistributedCoordinatorED_Developers_Guide.md"
    decimal-class: "19817"
    class-prefix: "1"
    individual-number: "APR 201 59/2"
    eri_document_type: "User Instruction"
    lang: "en"
    format: "pdf"
  - title: "Distributed Coordinator ED Test Specification"
    file: "./build/doc/test-specification/DistributedCoordinatorED_Test_Specification.pdf"
    source_files:
      - "./doc/test-specification/DistributedCoordinatorED_Test_Specification.md"
    decimal-class: "15241"
    class-prefix: "1"
    individual-number: "APR 201 59/2"
    eri_document_type: "Test Specification"
    lang: "en"
    format: "pdf"
  - title: "Distributed Coordinator ED Characteristics Report {semver}"
    file: "./characteristics_report.pdf"
    source_files:
      - "./characteristics_report.pdf"
    decimal-class: "152 83"
    class-prefix: "2"
    individual-number: "APR 201 59/2"
    strategy: "ordinal"
    eri_document_type: "Test Report"
    lang: "en"
    format: "pdf"
    eri_doc_responsible: "BDGS SA OSS"

