nmapConfig:
  services:
    - name: "eric-data-distributed-coordinator-ed"
      protocol:
        - "tcp"
        - "udp"
      additionalParams:
        - "-v"
        - "-p T:0-65535,U:1-1024"
        - "--stats-every 30"
    - name: "eric-data-distributed-coordinator-ed-agent"
      protocol:
        - "tcp"
        - "udp"
      additionalParams:
        - "-v"
        - "-p T:0-65535,U:1-1024"
        - "--stats-every 30"
  enableUnicornscan:
    additionalParams:
      - "-r300"
      - "-v"
  reportDir : "nmap_reports"
  enableServiceVersionDetection: true
