Kubesec:
  Product: "Data Distributed Coordinator Ed"
  Product_internal: "Data Distributed Coordinator Ed"
  Product_contact: "PDLPTEAMRA@pdl.internal.ericsson.com"
  KubesecYAML:
    Scan: true
    SkipTests: false
    armLinks: # Add the arm links that don't require authentication
      Links:
        - "https://arm.sero.gic.ericsson.se/artifactory/proj-adp-eric-data-dc-ed-drop-helm-local/eric-data-distributed-coordinator-ed/eric-data-distributed-coordinator-ed-VERSION.tgz"
      valuesOverride: # If override is needed we add values.yaml names in same order as arm links
        - ''
  KubesecCluster:
    Scan: false
    namespace: "${env.USER}"